### ISSUE TITLE
An interesting bug when disposing the vulkan objects

### ISSUE THREAD

**Issue by Iter123** [rhynodegreat/CSharpGameLibrary#3]
When disposing the objects out of order, it look like the program tries to find the specified object's file and fails to find it, as shown. When I do it in order, attempting to dispose the swapchain gives a System.AccessViolationException. I made sure that I disposed it verbatim from the samples. 

![image](https://user-images.githubusercontent.com/29178928/27413542-a6759020-56c1-11e7-8f94-4d1718401a4d.png)

**Comment by vazgriz** [comment]
Does the [sample repository](https://github.com/vazgriz/CSGL_Samples) build on your machine?
If so, could you post a [gist](https://gist.github.com/) of the code that created the above error?
Do you get the same error using the `0.1.0-alpha` package without the .pdbs?

**Comment by Iter123** [comment]
HelloTriangle seems to run fine, so I'm not sure why my program does not.

Without the .pbds it doesn't allow the program to go any further than during the disposing stage when closing the program, showing a Symbol Not Found page. This is the gist: https://gist.github.com/Iter123/88aef277c5b98335c3733a2b85bb0c2f. With the swapchain non-commented out it gives a System.AccessViolationException, like I said before

**Comment by vazgriz** [comment]
The problem is 
```
foreach (var iv in Program.swapchainImages)
    iv.Dispose();
```

You're disposing the swapchainImages, when you should be disposing the swapchainImageViews. That's causing the SystemAccessViolation when you try to dispose the swapchain.

As for the image, that's VS trying to find the source code for the Swapchain wrapper. It's not part of CSGL itself. I'm looking for ways to package the source code with the library, but for now you can point VS at a local copy of the source code if you have it.

**Comment by Iter123** [comment]
Aargh, it's always the stupid/small mistakes that catch me... Anyway thanks for the help
